name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: debian-latest
    
    strategy:
        fail-fast: true
    
    steps:
      - name: Install dependencies
        run: composer install
      
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
